"""add aritcle

Revision ID: 1454d41910b6
Revises: 84cdaba1bcb9
Create Date: 2025-07-16 14:05:26.708641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1454d41910b6'
down_revision: Union[str, Sequence[str], None] = '84cdaba1bcb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_extension',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('university', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_extension_id'), 'user_extension', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_extension_id'), table_name='user_extension')
    op.drop_table('user_extension')
    # ### end Alembic commands ###
